[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "frdfm-llm-tools"
version = "0.1.2"
description = "Simple LLM tools for commonly used local and remote providers."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GPL-3.0-or-later" }
authors = [
  { name = "Fereydoun Farrahi Moghaddam" }
]

dependencies = []

[project.urls]
Homepage = "https://github.com/frdfm/frdfm-llm-tools"

[tool.setuptools.packages.find]
where = ["."]
include = ["frdfm_llm_tools*"]
